/**
 * Bundled SQL Migrations
 * 
 * This file provides SQL migration content for environments
 * where file system reading isn't available (e.g., mobile).
 * 
 * AUTO-GENERATED - Update when adding new migrations
 */

export const sqlMigrations: Record<number, string> = {
  1548957970627: `BEGIN TRANSACTION;\n\nDROP TABLE db_version;\n\nCOMMIT;\n`,
  1550601598648: `BEGIN TRANSACTION;\n\nCREATE TABLE payees\n  (id TEXT PRIMARY KEY,\n   name TEXT,\n   category TEXT,\n   tombstone INTEGER DEFAULT 0,\n   transfer_acct TEXT);\n\nCREATE TABLE payee_rules\n  (id TEXT PRIMARY KEY,\n   payee_id TEXT,\n   type TEXT,\n   value TEXT,\n   tombstone INTEGER DEFAULT 0);\n\nCREATE INDEX payee_rules_lowercase_index ON payee_rules(LOWER(value));\n\nCREATE TABLE payee_mapping\n  (id TEXT PRIMARY KEY,\n   targetId TEXT);\n\nCOMMIT;\n`,
  1555786194328: `BEGIN TRANSACTION;\n\nCREATE TEMPORARY TABLE category_groups_tmp\n   (id TEXT PRIMARY KEY,\n    name TEXT UNIQUE,\n    is_income INTEGER DEFAULT 0,\n    sort_order REAL,\n    tombstone INTEGER DEFAULT 0);\n\nINSERT INTO category_groups_tmp SELECT * FROM category_groups;\n\nDROP TABLE category_groups;\n\nCREATE TABLE category_groups\n   (id TEXT PRIMARY KEY,\n    name TEXT,\n    is_income INTEGER DEFAULT 0,\n    sort_order REAL,\n    tombstone INTEGER DEFAULT 0);\n\nINSERT INTO category_groups SELECT * FROM category_groups_tmp;\n\nDROP TABLE category_groups_tmp;\n\nCOMMIT;\n`,
  1561751833510: `BEGIN TRANSACTION;\n\nCREATE INDEX trans_category_date ON transactions(category, date);\nCREATE INDEX trans_category ON transactions(category);\nCREATE INDEX trans_date ON transactions(date);\n\nCOMMIT;\n`,
  1567699552727: `BEGIN TRANSACTION;\n\nDELETE FROM spreadsheet_cells WHERE\n  name NOT LIKE '%!budget\_%' ESCAPE '\' AND\n  name NOT LIKE '%!carryover\_%' ESCAPE '\' AND\n  name NOT LIKE '%!buffered';\n\nUPDATE OR REPLACE spreadsheet_cells SET name = REPLACE(name, '_', '-');\n\nUPDATE OR REPLACE spreadsheet_cells SET\n  name =\n    SUBSTR(name, 1, 28) ||\n    '-' ||\n    SUBSTR(name, 29, 4) ||\n    '-' ||\n    SUBSTR(name, 33, 4) ||\n    '-' ||\n    SUBSTR(name, 37, 4) ||\n    '-' ||\n    SUBSTR(name, 41, 12)\nWHERE name LIKE '%!budget-%' AND LENGTH(name) = 52;\n\nUPDATE OR REPLACE spreadsheet_cells SET\n  name =\n    SUBSTR(name, 1, 31) ||\n    '-' ||\n    SUBSTR(name, 32, 4) ||\n    '-' ||\n    SUBSTR(name, 36, 4) ||\n    '-' ||\n    SUBSTR(name, 40, 4) ||\n    '-' ||\n    SUBSTR(name, 44, 12)\nWHERE name LIKE '%!carryover-%' AND LENGTH(name) = 55;\n\nUPDATE spreadsheet_cells SET expr = SUBSTR(expr, 2) WHERE name LIKE '%!carryover-%';\n\nCOMMIT;\n`,
  1582384163573: `BEGIN TRANSACTION;\n\nALTER TABLE transactions ADD COLUMN cleared INTEGER DEFAULT 1;\nALTER TABLE transactions ADD COLUMN pending INTEGER DEFAULT 0;\n\nCOMMIT;\n`,
  1597756566448: `BEGIN TRANSACTION;\n\nCREATE TABLE rules\n  (id TEXT PRIMARY KEY,\n   stage TEXT,\n   conditions TEXT,\n   actions TEXT,\n   tombstone INTEGER DEFAULT 0);\n\nCOMMIT;\n`,
  1608652596043: `BEGIN TRANSACTION;\n\nALTER TABLE transactions ADD COLUMN parent_id TEXT;\n\nUPDATE transactions SET\n  parent_id = CASE\n    WHEN isChild THEN SUBSTR(id, 1, INSTR(id, '/') - 1)\n    ELSE NULL\n  END;\n\nCREATE INDEX trans_parent_id ON transactions(parent_id);\n\nCOMMIT;\n`,
  1608652596044: `BEGIN TRANSACTION;\n\nDROP VIEW IF EXISTS v_transactions_layer2;\nCREATE VIEW v_transactions_layer2 AS\nSELECT\n  t.id AS id,\n  t.isParent AS is_parent,\n  t.isChild AS is_child,\n  t.acct AS account,\n  CASE WHEN t.isChild = 0 THEN NULL ELSE t.parent_id END AS parent_id,\n  CASE WHEN t.isParent = 1 THEN NULL ELSE cm.transferId END AS category,\n  pm.targetId AS payee,\n  t.imported_description AS imported_payee,\n  IFNULL(t.amount, 0) AS amount,\n  t.notes AS notes,\n  t.date AS date,\n  t.financial_id AS imported_id,\n  t.error AS error,\n  t.starting_balance_flag AS starting_balance_flag,\n  t.transferred_id AS transfer_id,\n  t.sort_order AS sort_order,\n  t.cleared AS cleared,\n  t.tombstone AS tombstone\nFROM transactions t\nLEFT JOIN category_mapping cm ON cm.id = t.category\nLEFT JOIN payee_mapping pm ON pm.id = t.description\nWHERE\n  t.date IS NOT NULL AND\n  t.acct IS NOT NULL;\n\nCREATE INDEX trans_sorted ON transactions(date desc, starting_balance_flag, sort_order desc, id);\n\nDROP VIEW IF EXISTS v_transactions_layer1;\nCREATE VIEW v_transactions_layer1 AS\nSELECT t.* FROM v_transactions_layer2 t\nLEFT JOIN transactions t2 ON (t.is_child = 1 AND t2.id = t.parent_id)\nWHERE IFNULL(t.tombstone, 0) = 0 AND IFNULL(t2.tombstone, 0) = 0;\n\nDROP VIEW IF EXISTS v_transactions;\nCREATE VIEW v_transactions AS\nSELECT t.* FROM v_transactions_layer1 t\nORDER BY t.date desc, t.starting_balance_flag, t.sort_order desc, t.id;\n\n\nDROP VIEW IF EXISTS v_categories;\nCREATE VIEW v_categories AS\nSELECT\n  id,\n  name,\n  is_income,\n  cat_group AS "group",\n  sort_order,\n  tombstone\nFROM categories;\n\nCOMMIT;\n`,
  1612625548236: `BEGIN TRANSACTION;\n\nCREATE INDEX messages_crdt_search ON messages_crdt(dataset, row, column, timestamp);\n\nANALYZE;\n\nCOMMIT;\n`,
  1614782639336: `BEGIN TRANSACTION;\n\n-- This adds the isChild/parent_id constraint in \`where\`\nDROP VIEW IF EXISTS v_transactions_layer2;\nCREATE VIEW v_transactions_layer2 AS\nSELECT\n  t.id AS id,\n  t.isParent AS is_parent,\n  t.isChild AS is_child,\n  t.acct AS account,\n  CASE WHEN t.isChild = 0 THEN NULL ELSE t.parent_id END AS parent_id,\n  CASE WHEN t.isParent = 1 THEN NULL ELSE cm.transferId END AS category,\n  pm.targetId AS payee,\n  t.imported_description AS imported_payee,\n  IFNULL(t.amount, 0) AS amount,\n  t.notes AS notes,\n  t.date AS date,\n  t.financial_id AS imported_id,\n  t.error AS error,\n  t.starting_balance_flag AS starting_balance_flag,\n  t.transferred_id AS transfer_id,\n  t.sort_order AS sort_order,\n  t.cleared AS cleared,\n  t.tombstone AS tombstone\nFROM transactions t\nLEFT JOIN category_mapping cm ON cm.id = t.category\nLEFT JOIN payee_mapping pm ON pm.id = t.description\nWHERE\n  t.date IS NOT NULL AND\n  t.acct IS NOT NULL AND\n  (t.isChild = 0 OR t.parent_id IS NOT NULL);\n\nCOMMIT;\n`,
  1615745967948: `BEGIN TRANSACTION;\n\nCREATE TABLE __meta__ (key TEXT PRIMARY KEY, value TEXT);\n\nDROP VIEW IF EXISTS v_transactions_layer2;\nDROP VIEW IF EXISTS v_transactions_layer1;\nDROP VIEW IF EXISTS v_transactions;\nDROP VIEW IF EXISTS v_categories;\n\nCOMMIT;\n`,
  1616167010796: `BEGIN TRANSACTION;\n\nALTER TABLE accounts ADD COLUMN sort_order REAL;\n\nCOMMIT;\n`,
  1618975177358: `BEGIN TRANSACTION;\n\nCREATE TABLE schedules\n  (id TEXT PRIMARY KEY,\n   rule TEXT,\n   active INTEGER DEFAULT 0,\n   completed INTEGER DEFAULT 0,\n   posts_transaction INTEGER DEFAULT 0,\n   tombstone INTEGER DEFAULT 0);\n\nCREATE TABLE schedules_next_date\n  (id TEXT PRIMARY KEY,\n   schedule_id TEXT,\n   local_next_date INTEGER,\n   local_next_date_ts INTEGER,\n   base_next_date INTEGER,\n   base_next_date_ts INTEGER);\n\nCREATE TABLE schedules_json_paths\n  (schedule_id TEXT PRIMARY KEY,\n   payee TEXT,\n   account TEXT,\n   amount TEXT,\n   date TEXT);\n\nALTER TABLE transactions ADD COLUMN schedule TEXT;\n\nCOMMIT;\n`,
  1679728867040: `BEGIN TRANSACTION;\n\nALTER TABLE rules ADD COLUMN conditions_op TEXT DEFAULT 'and';\n\nCOMMIT;\n`,
  1681115033845: `BEGIN TRANSACTION;\n\nALTER TABLE schedules ADD COLUMN name TEXT DEFAULT NULL;\n\nCOMMIT;\n`,
  1682974838138: `BEGIN TRANSACTION;\n\nDROP TABLE payee_rules;\n\nCOMMIT;\n`,
  1685007876842: `BEGIN TRANSACTION;\n\nALTER TABLE categories ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT 0;\nALTER TABLE category_groups ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT 0;\n\nCOMMIT;\n`,
  1686139660866: `BEGIN TRANSACTION;\n\nALTER TABLE accounts DROP COLUMN type;\n\nCOMMIT;\n`,
  1688749527273: `BEGIN TRANSACTION;\n\nCREATE TABLE transaction_filters\n  (id TEXT PRIMARY KEY,\n   name TEXT,\n   conditions TEXT,\n   conditions_op TEXT DEFAULT 'and',\n   tombstone INTEGER DEFAULT 0);\n\nCOMMIT;\n`,
  1688841238000: `BEGIN TRANSACTION;\n\nALTER TABLE accounts ADD COLUMN type TEXT;\n\nCOMMIT;\n`,
  1691233396000: `BEGIN TRANSACTION;\n\nALTER TABLE schedules_next_date ADD COLUMN tombstone INTEGER DEFAULT 0;\n\nCOMMIT;\n`,
  1694438752000: `BEGIN TRANSACTION;\n\nALTER TABLE zero_budgets ADD column goal INTEGER DEFAULT null;\nALTER TABLE reflect_budgets ADD column goal INTEGER DEFAULT null;\nALTER TABLE categories ADD column goal_def TEXT DEFAULT null;\n\nCOMMIT;\n`,
  1697046240000: `BEGIN TRANSACTION;\n\nALTER TABLE transactions ADD COLUMN reconciled INTEGER DEFAULT 0;\n\nCOMMIT;\n`,
  1704572023730: `BEGIN TRANSACTION;\n\nALTER TABLE accounts ADD COLUMN account_sync_source TEXT;\n\nCOMMIT;\n`,
  1704572023731: `BEGIN TRANSACTION;\n\nUPDATE accounts\nSET\n  account_sync_source = 'goCardless'\nWHERE account_id IS NOT NULL\n  AND account_sync_source IS NULL;\n\nCOMMIT;\n`,
  1707267033000: `BEGIN TRANSACTION;\n\nCREATE TABLE custom_reports\n  (\n    id TEXT PRIMARY KEY,\n    name TEXT,\n    start_date TEXT,\n    end_date TEXT,\n    date_static INTEGER DEFAULT 0,\n    date_range TEXT,\n    mode TEXT DEFAULT 'total',\n    group_by TEXT DEFAULT 'Category',\n    balance_type TEXT DEFAULT 'Expense',\n    show_empty INTEGER DEFAULT 0,\n    show_offbudget INTEGER DEFAULT 0,\n    show_hidden INTEGER DEFAULT 0,\n    show_uncategorized INTEGER DEFAULT 0,\n    selected_categories TEXT,\n    graph_type TEXT DEFAULT 'BarGraph',\n    conditions TEXT,\n    conditions_op TEXT DEFAULT 'and',\n    metadata TEXT,\n    interval TEXT DEFAULT 'Monthly',\n    color_scheme TEXT,\n    tombstone INTEGER DEFAULT 0\n  );\n\nCOMMIT;\n`,
  1712784523000: `BEGIN TRANSACTION;\n\nUPDATE category_groups\nSET\n  hidden = 0\nWHERE is_income = 1;\n\nCOMMIT;\n`,
  1716359441000: `BEGIN TRANSACTION;\n\nALTER TABLE custom_reports ADD COLUMN include_current INTEGER DEFAULT 0;\n\nCOMMIT;\n`,
  1720310586000: `BEGIN TRANSACTION;\n\nUPDATE transactions AS t1\nSET schedule = (\n    SELECT t2.schedule FROM transactions AS t2\n    WHERE t2.id = t1.transferred_id\n      AND t2.schedule IS NOT NULL\n    LIMIT 1\n)\nWHERE t1.schedule IS NULL\nAND t1.transferred_id IS NOT NULL\nAND EXISTS (\n  SELECT 1 FROM transactions AS t2\n  WHERE t2.id = t1.transferred_id\n    AND t2.schedule IS NOT NULL\n  LIMIT 1\n);\n\nCOMMIT;\n`,
  1720664867241: `BEGIN TRANSACTION;\n\nALTER TABLE payees ADD COLUMN favorite INTEGER DEFAULT 0 DEFAULT FALSE;\n\nCOMMIT;\n`,
  1720665000000: `BEGIN TRANSACTION;\n\nALTER TABLE zero_budgets ADD COLUMN long_goal INTEGER DEFAULT null;\nALTER TABLE reflect_budgets ADD COLUMN long_goal INTEGER DEFAULT null;\n\nCOMMIT;\n`,
  1730744182000: `BEGIN TRANSACTION;\n\nUPDATE dashboard\nSET tombstone = 1\nWHERE type is NULL;\n\nCOMMIT;\n`,
  1736640000000: `BEGIN TRANSACTION;\n\nALTER TABLE custom_reports ADD COLUMN sort_by TEXT DEFAULT 'Descending';\nUPDATE custom_reports SET sort_by = 'Descending';\nUPDATE custom_reports SET sort_by = 'Budget' where graph_type = 'TableGraph';\n\nCOMMIT;\n`,
  1737158400000: `BEGIN TRANSACTION;\n\nALTER TABLE payees ADD COLUMN learn_categories BOOLEAN DEFAULT 1;\n\nCOMMIT;\n`,
  1738491452000: `BEGIN TRANSACTION;\n\nALTER TABLE custom_reports RENAME COLUMN sort_by TO sort_by_old;\nALTER TABLE custom_reports ADD COLUMN sort_by TEXT DEFAULT 'desc';\n\nUPDATE custom_reports SET sort_by = 'desc' where sort_by_old = 'Descending';\nUPDATE custom_reports SET sort_by = 'asc' where sort_by_old = 'Ascending';\nUPDATE custom_reports SET sort_by = 'budget' where sort_by_old = 'Budget';\nUPDATE custom_reports SET sort_by = 'name' where sort_by_old = 'Name';\n\nALTER TABLE custom_reports DROP COLUMN sort_by_old;\n\nCOMMIT;\n`,
  1739139550000: `BEGIN TRANSACTION;\n\nALTER TABLE accounts ADD COLUMN last_sync text;\n\nALTER TABLE transactions ADD COLUMN raw_synced_data text;\n\nCOMMIT;\n`,
  1740506588539: `BEGIN TRANSACTION;\n\nALTER TABLE accounts ADD COLUMN last_reconciled text;\n\nCOMMIT;\n`,
  1745425408000: `BEGIN TRANSACTION;\n\nUPDATE preferences\nSET value = CASE WHEN id = 'budgetType' AND value = 'report' THEN 'tracking' ELSE 'envelope' END\nWHERE id = 'budgetType';\n\nCOMMIT;\n`,
  1749799110000: `BEGIN TRANSACTION;\n\nCREATE TABLE tags(\n  id TEXT PRIMARY KEY,\n  tag TEXT UNIQUE,\n  color TEXT,\n  description TEXT\n);\n\nCOMMIT\n`,
  1749799110001: `BEGIN TRANSACTION;\n\nALTER TABLE tags ADD COLUMN tombstone integer DEFAULT 0;\n\nCOMMIT;\n`,
  1754611200000: `-- Add a column to track where a category's automation templates come from\n-- Allowed values for source (by convention): 'notes' | 'ui'\nALTER TABLE categories ADD COLUMN template_settings JSON DEFAULT '{"source": "notes"}';\n\nUPDATE categories SET template_settings = '{"source": "ui"}' WHERE template_settings IS NULL;\n`,
  1759260219000: `-- Migration: Add trim_intervals column to custom_reports table\nBEGIN TRANSACTION;\n\nALTER TABLE custom_reports ADD COLUMN trim_intervals INTEGER DEFAULT 0;\n\nCOMMIT;\n`,
  1759842823172: `-- Migration removed because it was not needed\n`,
  1762178745667: `BEGIN TRANSACTION;\n\n-- Rename csv-skip-lines-* preferences to csv-skip-start-lines-*\nUPDATE preferences\nSET id = REPLACE(id, 'csv-skip-lines-', 'csv-skip-start-lines-')\nWHERE id LIKE 'csv-skip-lines-%';\n\nCOMMIT;\n`,
};
